{% set version = "8.0.1" %}
{% set ver = version.replace(".", "_") %}

package:
  name: esmf
  version: {{ version }}

source:
  git_url: https://github.com/esmf-org/esmf.git
  git_tag: ESMF_8_0_1

build:
  number: 1010
  skip: True  # [win]

requirements:
  build:
    - perl
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - netcdf-fortran
    - libnetcdf
    - hdf5
    - mpich
  run:
    - netcdf-fortran
    - libnetcdf
    - hdf5
    - mpich

test:
  commands:
    - ESMF_Info
    - ESMF_RegridWeightGen --help

about:
  home: http://www.earthsystemmodeling.org/
  license: University of Illinois/NCSA (NCSA)
  summary: |
    The Earth System Modeling Framework (ESMF) is software for building and
    coupling weather, climate, and related models.'

extra:
  recipe-maintainers:
    - ocefpaf
    - bekozi
    - rokuingh
