{% set version = "7.1.0r" %}
{% set ver = version.replace(".", "_") %}

package:
  name: esmf
  version: {{ version }}

source:
  git_url: git://git.code.sf.net/p/esmf/esmf
  git_tag: ESMF_7_1_0r

build:
  number: 1003
  skip: True  # [win]

requirements:
  build:
    - perl
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - netcdf-fortran
    - libnetcdf
    - hdf5
    - mpich
  run:
    - netcdf-fortran
    - libnetcdf
    - hdf5
    - mpich

test:
  commands:
    - ESMF_Info
    - ESMF_RegridWeightGen --help
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.earthsystemmodeling.org/
  license: University of Illinois/NCSA (NCSA)
  summary: 'The Earth System Modeling Framework (ESMF) is software for building and coupling weather, climate, and related models.'

extra:
  recipe-maintainers:
    - ocefpaf
    - bekozi
    - rokuingh
